class VersionGenerator:
    def __init__(self, applications):
        self.applications = applications
        # other version generator data

    def print_versions(self):
        for app in self.applications:
            print(app.version)

    def generate_versions(self):
        for app in self.applications:
            # generate version number for app based on its data
            version = self._calculate_version(app)
            app.version = version

    def _calculate_version(self, app):
        # calculate version number for app based on its data
        # and other factors

        version_controller = 'generated by VersionController'
        ver_num = 0
        ver = app.version
        if version_controller in ver:
            ver_li = ver.split(version_controller)
            if len(ver_li) == 2 and ver_li[1].strip().isdigit():
                ver_num = int(ver_li[1].strip())
                ver_num += 1
                ver = f'{ver_li[0]}'
            else:
                raise Exception('wronge version input')
        ver = f'{ver} {version_controller} {ver_num}'

        return ver
